name: chat_gpt_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  chat_gpt_sdk: ^2.1.2
  go_router: ^7.0.0
  responsive_framework: ^1.0.0
  injectable: ^2.1.1
  awesome_extensions: ^2.0.7
  animations: ^2.0.7
  get_it: ^7.3.0
  flutter_secure_storage: ^8.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:  
  build_runner:  
  import_sorter: ^4.6.0
  responsive_sizer: ^3.1.1


flutter:
  uses-material-design: true

# Run flutter pub run import_sorter:main
import_sorter:
  emojis: true # Optional, defaults to false
  comments: true # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - injectable_config.config.dart
    - injectable_config.dart
